# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Blog CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hexo GitHub Action
      uses: yrpang/github-actions-hexo@v1.3
      with:
        deploykey: ${{ secrets.GH_TOKEN }}
        username: Abingcbc
        email: abingcbc626@gmail.com
